### ISSUE TITLE
Please enable babel stage-0 features support

### ISSUE THREAD

**Issue by zephy358** [VictorBjelkholm/atom-react-preview#6]
Hi victor thank you for your awesome package. It's been really useful. But the problem is I'm writing react with ES7 syntax (async/ await and @ decorator), the require function in atom can't support ES7. I tried babel register to replace the original require function shipped with atom, but it didn't work. Some weird error occurred.  So I have to ask if you have any solution to this? I'd really appreciate it if you could add ES7 support.

**Comment by victorb** [comment]
Hey, version 2.0 of atom-react-preview have just been published. Shipped it with "react", "stage-0" and "es2015" presets so your components should work now. Please let me know if you still have any issues and we'll try to find a fix for it.

Thanks for the nice words :)
